export const DEADPOOL_COMIC_LOADING='DEADPOOL_COMIC_LOADING'
export const DEADPOOL_COMIC='DEADPOOL_COMIC'
export const DEADPOOL_COMIC_ERROR='DEADPOOL_COMIC_ERROR'


export const CHARACTER_INFO_LOADING='CHARACTER_INFO_LOADING'
export const CHARACTER_INFO='CHARACTER_INFO'
export const CHARACTER_INFO_ERROR='CHARACTER_INFO_ERROR'



export const INDIVIDUAL_COMIC_LOADING='INDIVIDUAL_COMIC_LOADING'
export const INDIVIDUAL_COMIC='INDIVIDUAL_COMIC'
export const INDIVIDUAL_COMIC_ERROR='INDIVIDUAL_COMIC_ERROR'